vich_uploader:
    db_driver: orm

    mappings:
        youtuber_image:
            uri_prefix: '%youtuber_image%'
            upload_destination: '%kernel.project_dir%/public%youtuber_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
